### ISSUE TITLE
Local host communication without Ethernet connection / no IPv6 address available

### ISSUE THREAD

**Issue by EduardPon** [ARMmbed/sal-stack-nanostack#14]
Hello,

We need a local host communication solution that is also working when the device has no IPv6 address assigned. We have a number of applications running on the device that communicate via UDP/CoAP.

Currently the local host communication mechanism works as long an IPv6 address was assigned before (router advertisement). Even when disconnecting from the Ethernet line, the local communication is kept operational.

So is there a way to get the local host communication operational when disconnected from a router advertisement or physically after a reboot? Thanks in advance.

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2723

**Comment by kjbracey-arm** [comment]
Unfortunately Nanostack doesn't have a dedicated loopback interface, or the loopback address ::1, but it will intercept and loop back self-addressed packets that are routed out of a real interface.

You may be able to use the link-local address of the Ethernet interface to talk to yourself in the absence of a border router, and hence absence of a global address, as long as the lack of response to RS packets doesn't force termination of the bootstrap.

**Comment by EduardPon** [comment]
Hello,

Thanks for your reply.

Currently I'm using the ::1 loop back address transferring CoAP messages and receiving these back. So the local host communication works fine. If the Nano stack does not do the loop back, who is? Nsdl?

**Comment by kjbracey-arm** [comment]
My slight mistake - Nanostack does recognise the address ::1 as being "for us", so that does activate the loopback logic in the interfaces. But unfortunately the packet does need to start on its way out of the device, and head to an interface.

In the absense of a real connection there may be no route to ::1, so the packet may be dropped for that reason. When the connection is up, it would be covered by the default route, so it would start heading out of the interface towards the default route, then be looped back as "for us".

Current versions of Nanostack do install specific on-link routes to our assigned addresses, allowing them to loop back without a default route, but ::1 is not covered by that.

You could try adding a static route to ::1 - mark it as "on-link" on an interface

    arm_net_route_add(loopback_addr, 128, NULL, 0xffffffff, 128, <interface id>);

**Comment by SeppoTakalo** [comment]
We have recorded this as a future architectural improvement to our stack and we will consider implementing this in future Nanostack releases.
However, it is not scheduled and we therefore can not promise any specific release when it will come.


As this is currently a missing implementation instead of issue, I will close this for now.

Thank you for you input.
