### ISSUE TITLE
How to adopt vendors MAC into mbed 6lowpan

### ISSUE THREAD

**Issue by liujian0927** [ARMmbed/sal-stack-nanostack#24]
In mac_api.h, there is a comment at the top: "A API class to support different MACs from multiple vendors."
I want to port CA8210, which is IEEE 802.15.4 transceiver ,to mbed.CA8210 has a full MAC in hardware that is controlled through MCPS/MLME.But,the 6LoWPAN and MAC layer were packed into library of mbed source code.So I don't know how to adopt vendors MAC into mbed 6lowpan. I‘m looking foward for your help. 
Thanks,
Jliu

cc @cyliangtw

**Comment by AnttiKauppila** [comment]
Hi Jliu,
What you need to do is 
1) implement an adapter, which implements functions defined in mac_api.h and returns mac_api_s pointer
 - 6LowPAN will internally call mac_initialize function to registers it's callbacks (e.g mcps_data_confirm)
 - Requests must be mapped with CA8210 MAC functions, like mcps_data_req -> adapter -> 8210_mcps_data_req
 - Callbacks from 8210 must call mac_api's callbacks, like 8210_mcps_data_conf -> adapter -> data_conf_cb
 - Adapter must handle data type transformations (if they differ between implementations)
2) initialize arm_nwk_interface_lowpan_init and pass mac_api_s pointer

How to test:
 - Check below classes and modify for your purposes (hw_mac instead of sw_mac):
 - In https://github.com/ARMmbed/mbed-os/blob/master/features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/source/ files nd_tasklet.c & LoWPANNDInterface.cpp

 - Modify mbed-os-example-mesh-minimal to follow your changes

BR,
Antti Kauppila

**Comment by liujian0927** [comment]
Hi Antti,

1. Is it necessary to call ns_sw_mac_create function before I call arm_nwk_interface_lowpan_init function,if I want to use CA8210 MAC?
2. Can I do not handle mac_storage_sizes_get pointer and parent_id variable? If it is necessary to handle them, could you tell me more details about them?
Thanks,
Jliu

**Comment by liujian0927** [comment]
Hi Antti,
1. Is it necessary to call ns_sw_mac_create function before I call arm_nwk_interface_lowpan_init function,if I want to use CA8210 MAC?
2. Can I do not handle mac_storage_sizes_get pointer and parent_id variable? If it is necessary to handle them, could you tell me more details about them?
Thanks,
Jliu
@AnttiKauppila

**Comment by AnttiKauppila** [comment]
Hi Jliu,

1. You don't need ns_sw_mac_create function. That just creates sw_mac in cases where you don't have HW_MAC. Replace that by a call to your CA8210_adapter_create() or similar.

2. mac_storage_size is used only for sw_mac, because there are no hardware limitations for table sizes.
In your case your HW_MAC should have those (Asked by Nanostack using MLME-GET). If CA8210 does not have any limits, you can set those also in your adapter if you want. This feature is used to prevent OOM situations in end products.

**Comment by liujian0927** [comment]
Hi Antti,
Thank you for your reply, I have another two questions.

1. I don't care about  parent_id this variable,when I use HW_MAC,is it right?

2. I found when  arm_nwk_interface_lowpan_init function is called,it will execute mac_initalize function. that will pass a mcps_data_confirm_handler function pointer to data_conf_cb and other confirm callback function pointers. So if I want to pass CA8210_mcps_data_conf function pointer to data_conf_cb ,it must be done after arm_nwk_interface_lowpan_init function have been executed,is it right?

Thanks,
Jliu

**Comment by liujian0927** [comment]
Hi Antti,
Thank you for your reply, I have another two questions.

I don't care about parent_id this variable,when I use HW_MAC,is it right?

I found when arm_nwk_interface_lowpan_init function is called,it will execute mac_initalize function. that will pass a mcps_data_confirm_handler function pointer to data_conf_cb and other confirm callback function pointers. So if I want to pass CA8210_mcps_data_conf function pointer to data_conf_cb ,it must be done after arm_nwk_interface_lowpan_init function have been executed,is it right?

Thanks,
Jliu
@AnttiKauppila

**Comment by AnttiKauppila** [comment]
Hi Jliu,

Yes, you are correct parent_id is not needed and initialize function must be called before hw_mac can use callback functions to upper layer.
