### ISSUE TITLE
Binary dumping ground only?

### ISSUE THREAD

**Issue by Stefan-Schmidt** [ARMmbed/sal-stack-nanostack#4]
Looking through this made me wonder why you would host this on github. It only contains binaries and header for API access.

If you don't want to open source this and foster a community around it hosting it on github is pointless imho.

**Comment by hugovincent** [comment]
Thanks for your comment Stefan. Because almost all of the rest of mbed OS is open source, GitHub is a good place for it. This one module is binary, but for consistency (in us releasing it, our users getting it, reporting bugs, etc), we prefer to host it here on Github too. In addition, our [mbed Parnters](https://www.mbed.com/en/partners/our-partners/) have source code access, and collaborate with us on it using a private GitHub repo. Thus, we think it makes sense overall for it to be here.

**Comment by Stefan-Schmidt** [comment]
To me it looks like for nobody but your partners this repo makes sense and they already have access to a private one. Given that the, for me, most interesting part of mbed OS is kept closed and only accessible to your paying partners makes my interest for it drop to zero. Guess I have to look elsewhere for a real OSS IoT OS.

Good luck with your commercial activities!

**Comment by OlegHahm** [comment]
Is there any reason why this part of mbed OS is binary only?

**Comment by OlegHahm** [comment]
ping

**Comment by OlegHahm** [comment]
ping
